apocalyptic-world/apocalyptic-world

t3lt.twee-config.yml
views/cabin/Event Baby merchant sell.tw
views/cabin/Scavenging - didnt came home.tw
views/cabin/Scavenging - look for girl dead.tw
views/cabin/Scavenging - look for girl fight lost.tw
views/cabin/Scavenging - look for girl fight.tw
views/cabin/Scavenging - look for girl not found.tw
views/explore/Explore event toxic waste.tw
views/explore/Explore event wolves.tw
views/farm/Vincent - sanctuary go #2.tw
views/game/Fight - lost.tw
views/npc/Girl - pregnancy potion.tw
views/npc/Guest move to basement.tw
views/outside/Guest house.tw
views/settlement/Rodger - horse get.tw
widgets/Widget - player.tw
widgets/Widget - sleep.tw

new widget guestRemove
- when removing guest companions must be updated
Also found typos and wrong variable name

guests.splice need companionRearrange

---

views/cabin/Event Rotten Rations.tw
views/cabin/Wood cabin.tw

Event can now trigger for slaves and guests
20% of food both in backpack and storage gets rotten

Rotten food fixes

---

js/npc/npc.js
js/onSaveLoad.js
js/scripts.js
views/npc/NPC info.tw
views/npc/customize/Girl customize - pierce boob remove.tw
views/npc/customize/Girl customize - pierce boob.tw
views/underground_city/Underground city - random event #2.tw
views/underground_city/nightclub/Nightclub - drink.tw
widgets/Widget actions.tw
widgets/Widget slaves.tw
widgets/npc/newgirl.tw
widgets/npc/newguy.tw
widgets/npc/newtransgirl.tw

- NPC eye color (% based on race and hair color, no game effect).
- NPC personality trait based on big 5 classification (no game effect).
- NPC age description adjustments (18-24: young, 40-59: mature, 60+: old).
- NPC sex actions subfolders renamed to allow more modding (the code will understand folders named : female.asian.young.pregnant, female.pregnant, transfemale.black, male.old)

eyes + personality + folder renaming

---

views/cabin/Basement - Offer slave guy to slave guy choose.tw
views/cabin/Basement - Offer slave guy to slave guy fuck.tw
views/npc/Guy view.tw

added Offer slave guy to slave guy  in the Basement, below is the link for the videos.
https://mega.nz/file/K7AWBC4C#S3dMhX0CDGUGuA85FqqVlT_wjGJxioaRDZVDozxEObM

adding Offer slave guy to slave guy

---

.vscode/settings.json
js/scripts.js
t3lt.twee-config.yml
views/game/Help - characters include.tw
views/game/Help - items include.tw
views/game/Help.tw
views/game/Inventory items.tw
views/game/Journal.tw

New clean branch for this so we can close pull request #38

Dynamic help for items + help cast

---

views/cabin/Basement - Offer slave trans girls to slave guy choose.tw
views/cabin/Basement - Offer slave trans girls to slave guy fuck.tw
views/npc/Guy view.tw

link below is the videos for the added code.
https://mega.nz/file/ur53DABI#VU8hUdmPm-ZPuAHVaP44zm4DBiMyLq9Mh5qZlSPilAc

added offer slave guy a slave trand girl.

---

views/blair/Blair - pregnant.tw
views/cabin/Event Baby merchant.tw
views/cabin/Event Food forager.tw
views/cabin/Event Kitchen stuck.tw
views/cabin/Event The uninvited couple.tw
views/cabin/Event guard caught intruder.tw
views/explore/Explore event Abandoned mall.tw
views/explore/Explore event Old couple.tw
views/explore/Explore event The Lost Child.tw
views/explore/Random event - beak humans #11 won.tw
views/explore/Random event - beak humans #11.tw
views/farm/Vincent - Infiltration of The Sanctuary.tw
views/underground_city/Dom - quest #3 2.tw
views/underground_city/Dom quest #2 2.tw
views/underground_city/Underground city - kids ball #3.tw

Godwill or goodwill?

---

js/scripts.js
views/cabin/Slave - wash.tw
views/npc/Girl - workout together.tw
views/npc/Girl view - guest.tw

Changes to girl workout to use regular sex actions.
New sexChance function, used in a few places (guest, workout, wash).

Workout and sexChance()

---

js/luna.js
views/outside/Forest - full moon include.tw
views/outside/Forest - mushrooms.tw
views/outside/Forest - new moon include.tw
views/outside/Forest-action-berries.tw
views/outside/Forest-action-chop-wood.tw
views/outside/Forest.tw

A little bonus for forest work at new or full moon.

Moon - fun in the forest

---

.gitignore
t3lt.twee-config.yml
views/explore/Explore event - Toxic cave.tw
views/npc/Girl view.tw
views/npc/Guest view assign to.tw
widgets/Widget - automatization.tw

t3lt.twee-config
It's start to get long and unreadable.
Another small thing...

Gaa mask + refactor t3lt.twee-config

---

views/npc/Girl invite - include.tw
views/npc/Girl view.tw
views/npc/fuck/Girl fuck - no.tw
views/underground_city/Wanted - catched.tw

I believe that these variables do not follow the same logic and it is not a good idea to use the same one for both needs.
I believe this considering the changes I made to the new fuck code.
In order to make the 'Force her' button work from inside the scene loop.

New $wasRaped seperate from $sexForced

---

js/onSaveLoad.js
views/cabin/Guesthouse [Event] - lesbian sex.tw
views/cabin/Workbench.tw
views/farm/Farm - shop.tw
views/game/Help - items include.tw
views/game/Workbench items.tw
views/npc/fuck/Mistress - Girl fuck - pussy.tw
views/sanctuary/Sanctuary shop.tw
views/settlement/Settlement - shop.tw
views/settlement_management/Settlement management.tw
views/settlement_management/Street workers.tw
views/underground_city/Underground shop.tw
widgets/Widget - shop.tw
widgets/Widget actions.tw
widgets/actionText.tw

- $workbenchItems → _workbenchItems and cache in setup.workbenchItems and unsets old variable
- Unsets  $shopItems when not in use
- actionText - $  → _, and cache unsetting $
Saves a little space in saves

Saving space in saves

---

js/npc/npc.js
t3lt.twee-config.yml
views/npc/Happy icon.tw
views/settlement_management/Info.tw
views/settlement_management/Street workers.tw
views/underground_city/Streets.tw

New branch, new pull request instead of #85
Info-tab
- [views/settlement_management/Info.tw](https://github.com/apocalyptic-world/apocalyptic-world/pull/86/files#diff-1dabcd3cc805d514b2a1768341c0d724f1ff591d4ceeda5b315dab9f31d883b1)
typos - Street workers
- [views/underground_city/Streets.tw](https://github.com/apocalyptic-world/apocalyptic-world/pull/86/files#diff-3c0236b1f2630ef4d88af0ab602501d595c7b41e53aacbd6f9328d7ad8accc16)
happpyIcon fixes
- [t3lt.twee-config.yml](https://github.com/apocalyptic-world/apocalyptic-world/pull/86/files#diff-b38c7372aadee3d0d4030a0efc6f42389dc9d160038ffacd067a4eab21c71f9d)
- [js/npc/npc.js](https://github.com/apocalyptic-world/apocalyptic-world/pull/86/files#diff-d62d3a759379e3329555a7435bb18d1c2c1e0604031473203eb2789d370d694c)
- [views/npc/Happy …

Random stuff

---

views/settlement_management/Info.tw

More Info-tab stuff

---

views/cabin/Bedrom - auto_morning.tw
views/game/Help.tw
views/settlement_management/Info.tw
views/settlement_management/Street workers.tw

[Help corrections](https://github.com/apocalyptic-world/apocalyptic-world/commit/ce28a627ce5c72ec0d6db3e7f20936e3da131e4a)
views\game\Help.tw
[typo Street workers](https://github.com/apocalyptic-world/apocalyptic-world/commit/29cf3b6bcfcd7f4f1d7b45ab18dd10853d849b8f)
views\settlement_management\Street workers.tw
[text change rule messages](https://github.com/apocalyptic-world/apocalyptic-world/pull/93/commits/0976c6ba147d244b4140268e89a7c601d0682942)
views\cabin\Bedrom - auto_morning.tw
[Today's birthdays on info-tab](https://github.com/apocalyptic-world/apocalyptic-world/pull/93/commits/5d914555a4afa41501f91cb73b9202d66307ece6)
views\settlement_management\Info.tw

Small things

---

views/cabin/Basement find.tw
views/cabin/Bedroom-sleep.tw
views/cabin/Blair - bedroom talk.tw
views/cabin/Blair - kitchen kiss.tw
views/cabin/Blair - kitchen talk.tw
views/cabin/Event The uninvited couple.tw
views/explore/Explore farm first time 1.3.tw
views/explore/Explore farm first time 1.4.tw
views/explore/Explore farm first time.tw
views/explore/Explore workbench - investigate.tw
views/explore/Explore workbench.tw
views/explore/Random event #15 ammo box.tw
views/explore/Random event - bikes #14 won.tw
views/explore/Random event - bikes #14.tw
views/farm/Farm - blair barn.tw
views/farm/Farm - quest delivery.tw
views/farm/Farm - talk about girl.tw
views/intro/Intro.tw
views/intro/Intro2.tw
views/intro/Intro3.tw
views/intro/Intro4.tw
views/outside/Fireplace - train strength.tw
views/settlement/Rodger - church talk.tw
views/settlement/Settlement - random event #1.tw
views/underground_city/Buy a round for everyone.tw

I liked the game, despite possessing some jank and only being in the process of adding true depth.  Despite that, the grammar primarily drew me out. Inconsistent tenses, typos, odd phrasings and the like. Since it's open source I figured I might as well address some of that.

Typo corrections and grammar changes.

---

views/cabin/Event The uninvited couple.tw

Adds a condition to the event to check if you actually have guests.

Add a condition to Event: The uninvited couple + minor grammar fix

---

js/scripts.js
js/traits.js
views/cabin/Basement - Offer slave girl to slave guy fuck.tw
views/npc/NPC marry evenging.tw
views/npc/fuck/mc/cum in pussy.tw
widgets/Widget - shop.tw

18-24 : 24%
25-39 : 16%
40-59 :   8%
breeder x2
fertility potion x2

Age base pregnancyChance function

---

views/cabin/Event Food forager.tw

- Improves dialogue in Event Food Forager
- Fixes misspelt Player.goodwill variables so it'll actually increase.

Event Food Forager: Dialogue changes + variable fixes

---

views/car/Garage.tw

Garage use cabinInventory

---

Magnus Castor - possible  todo.txt
js/automatization.js
js/items.js
js/scripts.js
views/cabin/Bedrom - auto_morning.tw
views/car/Garage.tw
views/farm/Farm - shop.tw
views/game/Help  - Guide include.tw
views/game/Help - characters include.tw
views/game/Help - items include.tw
views/game/Help.tw
views/game/Inventory items.tw
views/game/Journal.tw
views/npc/Guest view assign to.tw
views/sanctuary/Sanctuary shop.tw
views/settlement/Rodger - champagne.tw
views/settlement/Settlement - shop.tw
views/settlement_management/Info.tw
views/underground_city/Underground shop.tw
widgets/Widget - automatization.tw
widgets/Widget - sleep.tw

- Update of automatization rules. Buttplug, condom and dumbbell treated properly
- Info tab - pregnancy info + more info about production
- Help update
- Starting on guide/walkthrough
- refactor shopitems
- typo in widget - sleep, farm - shop, Journal. Rodger - champagne

Start play guide + Updates: Automatization + Info tab + help

---

Magnus Castor - possible  todo.txt
core/PassageReady.tw
js/onSaveLoad.js
js/player.js
js/scripts.js
t3lt.twee-config.yml
views/cabin/Blair - marry #2.tw
views/cabin/Childbirth.tw
views/game/Help  - Guide include.tw
views/game/Help - characters include.tw
views/game/Help.tw
views/npc/NPC marry.tw
views/sanctuary/Negan - fuel slaves.tw
views/settlement_management/Info.tw
views/settlement_management/Settlement management.tw
views/settlement_management/Test.tw
views/underground_city/Slave market.tw
widgets/Widget - player.tw
widgets/Widget - sleep.tw

+ More Game guide - all characters written
+ Hero family tree -- but only as a testpage under settlement management. Should have a better place!
+ typos
Help, Help characters
PassageReady
Settlement management - info
Widget - sleep
Slave market - added sanctuary found when 20 slaves sold.

Game guide - 10% + Hero family tree

---

js/npc/companion.js
views/explore/Explore event The Dying Elderly Survivor.tw

Extend Explore event

---

views/npc/NPC marry.tw

My bad. Where did that extra 'c' come from?

typo in NPC marry

---

js/automatization.js
t3lt.twee-config.yml
views/cabin/Basement.tw
views/cabin/Bedrom - auto_morning.tw
views/npc/Guest view assign to.tw
views/npc/NPC view.tw
widgets/Widget - automatization.tw

automatization support ...
..  slave companions
... body_armor
... assign to hunter with bow in storage

automatization updates

---

js/onSaveLoad.js
views/cabin/Youth district/Library built.tw
views/npc/Girl milk.tw

typos mentioned in f95

---

views/settlement_management/Info.tw

I saw you fixed the tax for stretworkers so I fixed the info in onfo-tab

Fix  Info-tab - Street workers money

---

js/help.js
js/onSaveLoad.js
js/player.js
js/scripts.js
views/cabin/Bedrom - auto_morning.tw
views/game/Help - items include.tw
views/game/Help.tw
views/outside/Forest - mushrooms.tw
views/settlement/Settlement - intro.tw
views/settlement_management/Info.tw
views/settlement_management/Test.tw

Family tree - Other's families
Info tab - Added teacher + update Streetwork money earned Mornings messages - Clarification
Help - fixes

Fixes - Family tree + Help + Info tab

---

js/family.js

Fix for isBloodToMC

---

js/automatization.js
views/cabin/Bedrom - auto_morning.tw
views/settlement_management/Automatization.tw
views/settlement_management/Street workers.tw

Sex worker auto rule now has levels not just on|off

Sex worker auto rule

---

js/cabin-inventory.js
js/family.js
js/npc/inventory.js
views/cabin/Bedrom - auto_morning.tw
views/cabin/Forest/Forest - fallen tree.tw
views/game/sleep/sleepShowTotals.tw

Fix fallen tree + small other fixes

---

js/automatization.js
views/cabin/Bedrom - auto_morning.tw
views/settlement_management/Automatization.tw

Buttplug rotation can be set by gender

Buttplug rotation by gender

---

js/onSaveLoad.js
js/player.js
views/cabin/Basement.tw
views/cabin/Blair - date [scavenging] fuck.tw
views/cabin/Blair - date [skyscraper] fuck.tw
views/cabin/Wood cabin.tw
views/cabin/Youth district/Library - read book.tw
views/isabel/Isabel - date [car ride].tw
views/outside/Greenhouse.tw
views/outside/Guest house.tw
views/settlement_management/Test.tw

**Fix pregnancy_father**
Checked for x.pregnancy_father where x.pregnancy = 0 in Blair and Isabel dates + 0nSaveLoad
**Fix heatwave & sandstorm**
Slave list in basement & guest list in guest house
**typo in wood cabin?**
- `tgenerateEnemiesrue `changed to `true`
plus your fixes also merged in
**Fixes Family tree**
Family tree many fixes
**Fixes Library - Read book**
----
~~**Fix common capital event**
common capital event called without enough girls in guest house~~

Fixes 0.40

---

js/help.js
js/onSaveLoad.js
js/player.js
js/skills.js
views/cabin/Childbirth.tw
views/game/Help  - Guide include.tw
views/game/Help.tw
views/settlement_management/Info.tw
views/settlement_management/Test.tw
widgets/Widget - sleep.tw
widgets/npc/childbirth.tw

Doctors-&-Hospital
- Updates help-, info- & auto-pages
Change of percentages
- Streets _miscarrieageChance: hospital 3%, any doctor 6%, else 12% 
- Sickday reduction: hospital 100%, any doctor 42%
- Bleeding: hospital, any doctor or bandage stops bleeding, as before 
- childbirth: chance of success: hospital 90% otherwise base 50%, towel +20%, amy doctor +20%

Doctors & Hospital

---

views/npc/NPC view - guest.tw
views/npc/NPC view.tw

fix energy girl milking

---

views/cabin/Scavenging - look for - alive.tw
views/game/Help  - Guide include.tw
views/game/Help - items include.tw
views/game/Help.tw
views/game/Inventory items.tw
views/npc/Guest view assign to.tw
widgets/sleep/Sleep - hospital.tw

His|Her fix scavenging - look for alive

Help update + fixes

---

views/npc/Guest view assign to.tw
views/npc/fuck/mistress/Texts/mistress_rimjob.js
views/npc/fuck/mistress/fuck.tw
widgets/npc/listView.tw

Transfemale mistress
also added a calendar icon instead of 'yo' to display age for guests.

Transfemale mistress

---

css/custom.css
js/npc/npc.js
views/npc/Mistress - Npc punish.tw
views/npc/NPC marry.tw
views/npc/NPC punish.tw
views/npc/NPC view.tw
views/npc/fuck/mistress/buttons.tw

Hello,
This little pull request contains 3 things :
VIRGIN INFO
- Adding a flower icon next to names of virgins in lists similarly to the married icon ([images.zip](https://github.com/user-attachments/files/16604075/images.zip)).
MARRIED SEX
- Adding to the married event a 'Fuck some more' button that launches regular sex
- Changes to the 'wedding' folder structure so as to use regular actions wording: You need to change the folder from fuck -> pussy for female and to anal for transfemale.
Note: I will expanded on this later (more wedding sex pictures + asking a wife to put her wedding dress on before regular fuck).
MISTRESS & PUNISHING
- Adding to the mistress fuck and punish view the possibility for mc to 'Take over', to continue himself.
Note: for compatibility reasons I had to remove …

Misc changes

---

views/cabin/Kitchen-room.tw
views/outside/Guest house.tw
views/settlement_management/Info.tw
views/underground_city/Fight cage/Fight cage - fight #2.tw
widgets/Widget - sleep.tw

milk_barn: added info on info tab + milk info in widget sleep
fix for fight cage fight 2 -- forgotten variable

v0.44 fixes

---

widgets/Widget - sleep.tw
widgets/sleep/Sleep - hospital.tw

small fix - Hospitals can handle multiple births on  a day

Hospitals can handle multiple births

---

js/events.js
js/onSaveLoad.js
js/scripts.js
views/cabin/Bedrom - auto_morning.tw
views/settlement_management/Info.tw

minor fix for fraction numbers
fix dairy cattle day off
fix fight cage rank for very old saves

Fixes 0.45

---

views/npc/fuck/mc/Texts/female/anal_reverse.js
views/npc/fuck/mc/Texts/female/anal_reverse_cum.js
views/npc/fuck/mc/Texts/female/pussy.js
views/npc/fuck/mc/Texts/male/male_texts.js
views/npc/fuck/mc/Texts/transfemale/transmale_texts.js
views/npc/fuck/mc/buttons.tw
views/npc/fuck/mc/fuck.tw

anal on mc
https://github.com/user-attachments/files/16841547/images_anal_mc.zip

anal on mc

---

js/onSaveLoad.js
views/settlement_management/Info.tw

Fix 0.45 saves dumberbell -> kettlebell.

Fix 0.45 saves dumberbell -> kettlebell.

---

views/npc/fuck/mc/Texts/female/bj_reverse.js
views/npc/fuck/mc/Texts/male/male_texts.js
views/npc/fuck/mc/Texts/transfemale/transmale_texts.js
views/npc/fuck/mc/fuck.tw

Hey,
Added bj_reverse (mc giving a blowjob)
Adjustments on anal_reverse
Icon and a few images :
[bj_reverse.zip](https://github.com/user-attachments/files/17480795/bj_reverse.zip)
CU

bj reverse

---

views/npc/fuck/mc/Texts/female/bj_reverse.js
views/npc/fuck/mc/Texts/female/sn.js
views/npc/fuck/mc/Texts/male/male_texts.js
views/npc/fuck/mc/Texts/transfemale/transmale_texts.js
views/npc/fuck/mc/fuck.tw

1) I added the 69 fuck action, a couple of images: 
[images.zip](https://github.com/user-attachments/files/17604503/images.zip)
2) I also took the opportunity to review all the fuck actions and try to:
- put fields in same order
- follow a similar logic for analsluts everywhere
- put the reverse actions at the end

sixty-nine and fuck action cleaning up

---

js/automatization.js
views/cabin/Basement.tw
views/fight/Fight - after companions.tw
views/game/Help  - Guide include.tw
widgets/Widget - fight.tw

Merry X-mas!
minor fix text for auto condom
placeholder comments

Placeholder comments

---

views/game/sleep/sleepDumbbell.tw
widgets/Widget - sleep.tw

Less risk of training damage

---

js/help.js
js/npc/npc.js
views/game/Help  - Guide include.tw
views/settlement_management/Test.tw

Started update the family tree tab
+ fixes for help

Family tree update start

---

core/Story JavaScript.tw
views/cabin/Bedroom-sleep.tw
views/npc/fuck/mc/Texts/female/anal_fisting.js
views/npc/fuck/mc/Texts/female/pussy_fisting.js
views/npc/fuck/mc/actions.tw
views/npc/fuck/mc/orgasm.tw
widgets/Widget actions.tw

[images.zip](https://github.com/user-attachments/files/18486746/images.zip)

pussy fisting + trans orgasm + dream options

---

views/game/Help/Help  - Guide include.tw
widgets/Widget - fight.tw

**Small Fight update**
allys choose attack
+ small __ fix
**typos Help _ Guide**

Small Fight update + typos Help _ Guide

---

views/game/Help/Help  - Guide include.tw
widgets/Widget - fight.tw

More small fixes. You are too fast....

Help Guide

---

widgets/Widget - sleep.tw

Fixed increment counter when finding random mushrooms.

Update Widget - sleep.tw

---

views/cabin/Basement/Group workout - slaves.tw

Fixing error in slave group workout, reported by Khaifirst on Discord.

Update Group workout - slaves.tw

---

views/car/Car explore event - gypsy family lost.tw
views/car/Car explore event - gypsy family won.tw
views/car/Car explore event - gypsy family.tw

Added options to invite or capture the daughter or both of them.

Update Car explore event - gypsy family.tw

---

views/cabin/Shower - threesome.tw

Update Shower - threesome.tw

---

views/cabin/Guesthouse - Ask for threesome choose.tw
views/npc/NPC view - guest.tw
views/npc/fuck/mc/Texts/female/threesome.js
views/npc/fuck/mc/Texts/transfemale/transfemale_texts.js
views/npc/fuck/mc_threesome/actions.tw
views/npc/fuck/mc_threesome/buttons.tw

Guest threesome for "mc + girl + tgirl"
Base images with girl and tgirl focus, plus action icons here (more in pack.):
https://pixeldrain.com/u/y7JYcezY

mft & mtf for mc

---

views/outside/Guest house.tw

Added clickable headers to the Guest house to sort by Name, Assignment or Arrival (default).

Update Guest house.tw

---

views/car/Car - Explore.tw

Added logic to trigger car breakdown event, triggered randomly based on level of vehicle damage.

Update Car - Explore.tw

---

views/car/Car breakdown event - Engine Failure.tw
views/explore/Explore event - Wicked family.tw

Added ability to either trade for the young woman's freedom (without having sex) or buy her as a slave (after sex). Also, fixed the event so that it subtracts food and wood from inventory when you give it to the old couple.  Makes sense to get some goodwill too.

Update Explore event - Wicked family.tw

---

views/explore/Explore event - Wicked family daughter.tw

Added options to either rescue the young woman (guest) or buy her (slave).

Update Explore event - Wicked family daughter.tw

---

views/underground_city/Fight cage/NPC fight/Fight - finished.tw

Added victory and defeat lines for the NPCs when they finish a match in the fight club.

Update Fight - finished.tw
